# Python Pandas Working With XML

1. Read XML and get Dataframe
2. Convert Dataframe to XML

What is XML?

1. XML stands for eXtensible Markup Language
2. XML is a markup language much like HTML
3. XML was designed to store and transport data
4. XML was designed to be self-descriptive
5. XML is a W3C Recommendation

In [5]:
import pandas as pd
from io import StringIO

pd.read_xml('test.xml')  # read XML file and convert to pandas DataFrame

      shape  degrees  sides
0    square      360    4.0
1    circle      360    NaN
2  triangle      180    3.0

In [10]:
# using string
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data xmlns="http://example.com">
 <row>
   <shape>square</shape>
   <degrees>360</degrees>
   <sides>4.0</sides>
   <firstname>Sadman</firstname>
 </row>
 <row>
   <shape>circle</shape>
   <degrees>360</degrees>
   <sides/>
   <firstname/>
 </row>
 <row>
   <shape>triangle</shape>
   <degrees>180</degrees>
   <sides>3.0</sides>
   <firstname/>
 </row>
</data>'''

df = pd.read_xml(StringIO(xml))  # read XML from string and convert to pandas DataFrame
df

      shape  degrees  sides firstname
0    square      360    4.0    Sadman
1    circle      360    NaN      None
2  triangle      180    3.0      None

we can use XML validator to check if the xml file is valid

In [ ]:
print("hello")