# Pandas Read CSV Files, StringIO

In [2]:
from io import StringIO

import pandas as pd
import numpy as np

df = pd.read_csv("Formula.csv")         # Reading CSV file ( converts CSV to DataFrame )
print(type(df))

print(df)
print("\n")

<class 'pandas.core.frame.DataFrame'>
   Table  Constructor  Points
0     11      McLaren     684
1     22     Mercedes     543
2     33      RedBull     532
3     44      Ferrari     489
4     55  AstonMartin     323

String -> CSV File -> DataFrame

In [3]:
# convert string to in memory file format object

data = ("Col1,Col2,Col3\n"
        "x,y,1\n"
        "a,b,2\n"
        "c,d,3\n")



string_io_data = StringIO(data)
print(type(string_io_data))
df2 = pd.read_csv(string_io_data,sep = ",")  # Reading CSV from in memory file object
print(df2)
print("\n")


# or directly
#df3 = pd.read_csv(StringIO(data), sep = ",")
df3 = pd.read_csv(StringIO(data))           # sep = "," is default for CSV
print(df3)

<class '_io.StringIO'>
  Col1 Col2  Col3
0    x    y     1
1    a    b     2
2    c    d     3


  Col1 Col2  Col3
0    x    y     1
1    a    b     2
2    c    d     3

In [4]:
# usecols -> to read specific columns from CSV
pd.read_csv(StringIO(data), usecols = ["Col1","Col3"])

  Col1  Col3
0    x     1
1    a     2
2    c     3

In [5]:
df = pd.read_csv(StringIO(data), dtype = {"Col3": float})   # specify data type of a column
print(df)

df.info()    # get info about dataframe

  Col1 Col2  Col3
0    x    y   1.0
1    a    b   2.0
2    c    d   3.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    3 non-null      object
 1   Col2    3 non-null      object
 2   Col3    3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 204.0+ bytes

In [6]:
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False  False  False
2  False  False  False

In [7]:
# Select element using indexing
print(df.iloc[1,2])   # 2nd row, 3rd column

print(df["Col3"][1])

print(df)

2.0
2.0
  Col1 Col2  Col3
0    x    y   1.0
1    a    b   2.0
2    c    d   3.0

In [8]:
data = ("Col1,Col2,Col3\n"
        "1,2,3\n"
        "4,5,6\n"
        "7,8,9\n")

df = pd.read_csv(StringIO(data), dtype = {"Col1": int, "Col2": float, "Col3": int})   # specify data type of a column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    3 non-null      int64
 1   Col2    3 non-null      float64
 2   Col3    3 non-null      int64
dtypes: float64(1), int64(2)
memory usage: 204.0 bytes

Create CSV file from dataframe

In [9]:
ndf = pd.read_csv(StringIO(data), usecols = ["Col1","Col3"])
print(ndf)
print("\n")

# Create CSV file
ndf.to_csv("NewFile.csv", index = False)   # index = False to avoid writing index column

   Col1  Col3
0     1     3
1     4     6
2     7     9

(Index_col): to treat a column as index

In [10]:
data = ("Index,Col1,Col2,Col3\n"
        "24,1,2,3\n"
        "25,4,5,6\n"
        "26,7,8,9\n")
pd.read_csv(StringIO(data), index_col = 0)   # (Index_col): to treat a column as index

       Col1  Col2  Col3
Index
24        1     2     3
25        4     5     6
26        7     8     9

In [11]:
print(pd.read_csv("Formula.csv"))           # use default 1,2,3,4 for index

pd.read_csv("Formula.csv", index_col = "Table" """ index_col = 0 """,usecols = ["Constructor","Points","Table"] )         # set 'Table' column as index while reading CSV

   Table  Constructor  Points
0     11      McLaren     684
1     22     Mercedes     543
2     33      RedBull     532
3     44      Ferrari     489
4     55  AstonMartin     323

ValueError: Index Table index_col = 0  invalid